# Google App Engine設定ファイル（代替デプロイ方法）
runtime: custom
env: flex

# 自動スケーリング設定
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10
  cool_down_period_sec: 120
  target_cpu_utilization: 0.6

# リソース設定
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# 環境変数
env_variables:
  NODE_ENV: production
  VITE_LLM_ENDPOINT: https://api.openai.com/v1/chat/completions

# ヘルスチェック
liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300